# Develop
spring:
  profiles: "dev"

  datasource:
    url:
    username:
    password:
    testWhileIdle: "true"
    validationQuery: "SELECT 1"

# Location of assets for training program
training:
  laughterSamples: "/Users/milesdowe/Documents/workspace/school/laugh-finder/laugh-files/laughter_filenames.txt"
  nonLaughterSamples: "/Users/milesdowe/Documents/workspace/school/laugh-finder/laugh-files/non_laughter_filenames.txt"
  # Location of the Python training script to run
  program:
    path: "/Users/milesdowe/Documents/workspace/school/laugh-finder/python-training/main.py"
  # Location of the .arff output file (used to generate model)
  arff:
    path: "C:/Users/Miles/Documents/workspace/lf-output/wekaFile.arff"
  # Location of model, resulting from k-NN analysis
  model:
    path: "C:/Users/Miles/Documents/workspace/lf-output/laugh.model"

# Location of assets for testing program
testing:
  mainScript: "C:/Users/Miles/Documents/workspace/laugh-finder-service/ml-scripts/python-testing/main.py"
  arff:
    path: "C:/Users/Miles/Documents/workspace/lf-output/test.arff"
  index:
    path: "C:/Users/Miles/Documents/workspace/lf-output/index.txt"
  window: "800"

# TODO: State shouldn't be maintained in external files, should be in database
testDir: "C:/Users/Miles/Documents/workspace/lf-output"

# Are these necessary?
python:
  win:
    path: "C:\\Users\\Miles\\AppData\\Local\\Programs\\Python\\Python35-32\\python.exe"
  nix:
    path: "/usr/local/bin/python"

server:
  port: 8080
