# Develop
spring:
  profiles: "dev"
assets:
  video:
    # where video files are located for extracting (multiple variables for multiple S3 buckets? not very maintainable...)
    inputPath: "../test-videos/"
  audio:
    # where audio files are placed for scanning
    outputPath: "../test-videos/"
dependencies:
  ffmpeg:
    win:
      location: "C:\\Program Files (x86)\\ffmpeg\\bin\\ffmpeg.exe"
    nix:
      location: "/usr/local/Cellar/ffmpeg/2.8.4/bin/ffmpeg"
server:
  port: 8080
