# Develop

baseDir: "/home/miles/Documents/workspace"

spring:
  datasource:
    driver-class-name: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/uwbwfe"
    username: "root"
    password: "ImJustAMachine?!"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"


retrainScript: "{{baseDir}}/lf-python-scripts/training/main.py"

training:
  model:
    path: "{{baseDir}}/lf-model-files/laugh.model"

# Location of assets for testing program
testing:
  mainScript: "{{baseDir}}/lf-python-scripts/testing/main.py"
  arff:
    path: "{{baseDir}}/lf-model-files/test.arff"
  index:
    path: "{{baseDir}}/lf-model-files/index.txt"
  window: "800"

# TODO: State shouldn't be maintained in external files, should be in database
testDir: "{{baseDir}}/lf-model-files"

server:
  port: 16000
