package edu.uw.citw.util.weka;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;
import weka.classifiers.Evaluation;
import weka.classifiers.lazy.IBk;
import weka.core.Instances;
import weka.core.SerializationHelper;
import weka.core.converters.ConverterUtils;

import javax.annotation.Nonnull;
import java.io.InputStream;
import java.util.Random;


/**
 * Weka is a data-mining tool developed by the University of Waikato. This util uses the Weka API to translate
 * the *.arff file generated by the "training" Python script into a usable model.
 *
 * Created by milesdowe on 7/4/16.
 */
@Component
public class WekaModelUtil {

    private static Logger log = LoggerFactory.getLogger(WekaModelUtil.class);


    public Instances readArff(@Nonnull InputStream inputData) throws Exception {
        ConverterUtils.DataSource source = new ConverterUtils.DataSource(inputData);
        return getInstances(source);
    }


    public Instances readArff(@Nonnull String filepath) throws Exception {
        ConverterUtils.DataSource source = new ConverterUtils.DataSource(filepath);
        return getInstances(source);
    }


    private Instances getInstances(ConverterUtils.DataSource source) throws Exception {
        Instances data = source.getDataSet();
        data.setClassIndex(data.numAttributes() - 1);
        data.setRelationName("Laughter_detection_capture_training");
        return data;
    }


    public IBk classifyAndGetModel(@Nonnull String filepath) throws Exception {
        Instances data = readArff(filepath);
        return processData(data);
    }


    public IBk classifyAndGetModel(@Nonnull InputStream inputData) throws Exception {
        Instances data = readArff(inputData);
        return processData(data);
    }


    private IBk processData(Instances data) throws Exception {
        // Going to do this Shalini's way
        IBk iBk = new IBk(6);
        Evaluation eval = new Evaluation(data);
        eval.crossValidateModel(iBk, data, 10, new Random(1));
        iBk.buildClassifier(data);

        return iBk;
    }


    public void saveModel(@Nonnull String modelOutputPath, @Nonnull IBk iBk) throws Exception {
        SerializationHelper.write(modelOutputPath, iBk);
    }
}
